# Generated by Django 4.2.27 on 2025-12-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("tmdb_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("tmdb_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("original_title", models.CharField(blank=True, max_length=500, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("poster_path", models.CharField(blank=True, max_length=255, null=True)),
                ("backdrop_path", models.CharField(blank=True, max_length=255, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("vote_average", models.FloatField(default=0)),
                ("vote_count", models.IntegerField(default=0)),
                ("genres", models.JSONField(default=list)),
                ("keywords", models.JSONField(default=list)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("tagline", models.TextField(blank=True, null=True)),
                ("popularity", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "movies",
                "ordering": ["-popularity"],
            },
        ),
    ]
