# Generated by Django 4.2.27 on 2025-12-25 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("movielens_user_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_cold_start", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "app_users",
            },
        ),
        migrations.CreateModel(
            name="WatchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tmdb_id", models.IntegerField()),
                ("watched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="watch_history", to="users.appuser"
                    ),
                ),
            ],
            options={
                "db_table": "watch_history",
                "ordering": ["-watched_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "preference_type",
                    models.CharField(
                        choices=[("genre", "Genre"), ("keyword", "Keyword"), ("actor", "Actor"), ("director", "Director")],
                        max_length=50,
                    ),
                ),
                ("preference_value", models.CharField(max_length=255)),
                ("weight", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to="users.appuser"
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tmdb_id", models.IntegerField()),
                ("rating", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="users.appuser"),
                ),
            ],
            options={
                "db_table": "user_ratings",
                "unique_together": {("user", "tmdb_id")},
            },
        ),
    ]
